version: '3'
services:
  app:
    container_name: postgres_with_gin_api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db-postgres
    networks:
      - app


  fullstack-postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=posgtres
      - POSTGRES_DB=users
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - app
